---
lessonName: Using Robot Framework for Automated Testing
lessonId: 29
category: tools
lessondiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/lesson-29/lessondiagram.png
tier: prod
prereqs:
  - 24  # PyEZ
description: Robot is a popular testing framework, allowing users to define testing workflows with plain language and keywords. In this lesson we'll cover an introduction to Robot as well as how to write test cases for Junos network devices.
slug: Robot Framework
tags:
- robot
- testing

utilities:
- name: linux1
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1

connections:
- a: vqfx1
  b: linux1

stages:
  - id: 1
    description: Introduction to Robot Framework

  - id: 2
    description: Writing Testcases for Junos Devices

  - id: 3
    description: Robot Framework - Best Practices
