---
lessonName: Device Specific Template Generation
lessonId: 35
lessonDiagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/lesson-35/lessondiagram.png
category: workflows
tier: prod
prereqs:
  - 23  # Linux
  - 14  # Yaml
  - 16  # Jinja2
description: Having the ability to generate device specific configurations from an approved device template can be beneficial especially for new deployments. 
slug: TEMPLATEGEN
tags:
- pyez
- yaml
- jinja2

utilities:
- name: linux
  image: antidotelabs/utility

devices:
- name: vqfx1
  image: antidotelabs/vqfx:snap1
  ports: [830]
- name: vqfx2
  image: antidotelabs/vqfx:snap2
  ports: [830]

stages:
  - id: 1
    description: Skills Review
  - id: 2
    description: Multiple Devices
  - id: 3
    description: Multiple Devices w/ Uplinks
  - id: 4
    description: Push Generated Configs
