---
lessonName: Automating an EVPN-VXLAN Fabric
lessonId: 36
category: workflows
lessondiagram: 
tier: prod
prereqs:
  - 23  # Linux
description: In this lesson, we will look into automating an EVPN/VXLAN fabric
slug: What is this
tags:
- troubleshooting
- tshoot


endpoints:
- name: spine
  image: antidotelabs/vqfx-full:18.1R1.9
  presentations:
          - name: cli
            port: 22
            type: ssh
  additionalPorts: [830]
  configurationType: napalm-junos

- name: leaf1
  image: antidotelabs/vqfx-full:18.1R1.9
  presentations:
          - name: cli
            port: 22
            type: ssh
  additionalPorts: [830]
  configurationType: napalm-junos

- name: leaf2
  image: antidotelabs/vqfx-full:18.1R1.9
  presentations:
          - name: cli
            port: 22
            type: ssh
  additionalPorts: [830]
  configurationType: napalm-junos
  
- name: linux1
  image: antidotelabs/utility
  presentations:
          - name: cli
            port: 22
            type: ssh

- name: linux2
  image: antidotelabs/utility
  presentations:
          - name: cli
            port: 22
            type: ssh

connections:
- a: spine
  b: leaf1
- a: spine
  b: leaf2
- a: leaf1
  b: linux1
- a: leaf2
  b: linux2


stages:
  - id: 1
    description: Explore EVPN VXLAN fabric and configuration

